export const stage1En = [
  {
    slug: "print",
    number: "1-1",
    title: "Voice Rune",
    topic: "print()",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "Greetings, apprentice! I'm Lexa. Today the machine will learn to speak." },
      { character: "Dash", text: "Your first mission is to make the machine pronounce a greeting!" },
    ],
    explanation:
      "`print()` is the 'show on screen' command. Inside the parentheses, write text in quotes, and the machine displays it on the panel.",
    codeExample: `print("Hello, workshop!")`,
    glitchTrap: {
      brokenCode: `print(Hello)`,
      problem: "Text without quotes.",
      fix: 'print("Hello")',
    },
    mission: "Print three lines:\n1. My name is ...\n2. I came to start the machine\n3. Python Quest begins!",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ['print("', 'print("'] }),
    quiz: {
      question: "What does print() do?",
      options: ["saves a number", "shows text on the screen", "asks for an answer"],
      correctIndex: 1,
    },
    rewardAbility: "Voice Rune",
  },
  {
    slug: "strings",
    number: "1-2",
    title: "Seal of Words",
    topic: "strings and quotes",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "Words must be 'sealed' in quotes. Otherwise the machine won't understand it's text." },
      { character: "Silas", text: "Let us verify precision. Quotes are a frame for text." },
    ],
    explanation: "A string is text. In Python, text is always in quotes: double or single.",
    codeExample: `print("I am a hero")`,
    glitchTrap: {
      brokenCode: `print("I'm a hero')`,
      problem: "Different quotes.",
      fix: `print("I'm a hero")`,
    },
    mission: "Print the hero's name, the workshop name, and the door password.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ['print("', 'print("', 'print("'] }),
    quiz: {
      question: "Where is the text written correctly?",
      options: ["print(Hello)", 'print("Hello")', "print Hello"],
      correctIndex: 1,
    },
    rewardAbility: "Seal of Words",
  },
  {
    slug: "variables",
    number: "1-3",
    title: "Memory Flask",
    topic: "variables",
    mainCharacter: "Lyra",
    dialogue: [
      { character: "Lyra", text: "A variable is a memory flask with a name. Put a value in — use it later." },
    ],
    explanation: "Variable = a box/flask with a name. On the left is the name, on the right is the value, = means 'put'.",
    codeExample: `hero_name = "Arin"\nprint(hero_name)`,
    glitchTrap: {
      brokenCode: `hero name = "Arin"`,
      problem: "Space in the variable name.",
      fix: 'hero_name = "Arin"',
    },
    mission: "Create variables hero_name, city_name, pet_name and print them.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["=", "print("] }),
    quiz: {
      question: "What is inside the variable power = 5?",
      options: ["the name power", "the number 5", "the word print"],
      correctIndex: 1,
    },
    rewardAbility: "Memory Flask",
  },
  {
    slug: "input",
    number: "1-4",
    title: "Listening Gate",
    topic: "input()",
    mainCharacter: "Dash",
    dialogue: [
      { character: "Dash", text: "The machine must listen! The input() command asks a question and waits for an answer." },
    ],
    explanation: "`input()` — the machine asks a question and waits for the player's answer. It's better to save the answer in a variable.",
    codeExample: `name = input("What is your name? ")\nprint(name)`,
    glitchTrap: {
      brokenCode: `input(What is your name?)`,
      problem: "Question without quotes.",
      fix: 'input("What is your name? ")',
    },
    mission: "Ask for name, favorite color, and pet's name. Then print the answers.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["input(", "print("] }),
    quiz: {
      question: "Where is it best to save the player's answer?",
      options: ["in a variable", "in quotes", "in a comment"],
      correctIndex: 0,
    },
    rewardAbility: "Listening Gate",
  },
  {
    slug: "int-input",
    number: "1-5",
    title: "Number Converter",
    topic: "int(input())",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "input() gets text. But if you need a number — convert the text to a number with int()." },
    ],
    explanation: "`input()` gives text. `int()` converts text to a number. Wrap one inside the other.",
    codeExample: `age = int(input("How old are you? "))`,
    glitchTrap: {
      brokenCode: `age = input("How old are you? ")\nnext_age = age + 1`,
      problem: "age is still text. You can't add text and a number.",
      fix: `age = int(input("How old are you? "))\nnext_age = age + 1`,
    },
    mission: "Ask for age, number of keys, and crystals. Save them as numbers.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["int(input(", "="] }),
    quiz: {
      question: "Why do we need int()?",
      options: ["to display text", "to turn text into a number", "to create a condition"],
      correctIndex: 1,
    },
    rewardAbility: "Number Converter",
  },
  {
    slug: "arithmetic",
    number: "1-6",
    title: "Gear of Counting",
    topic: "arithmetic",
    mainCharacter: "Dash",
    dialogue: [
      { character: "Dash", text: "The counting gears are turning! Python can add, subtract, multiply, and divide." },
      { character: "Silas", text: "But be careful: numbers and text behave differently." },
    ],
    explanation: "Arithmetic counts resources. Add crystals, subtract spent keys.",
    codeExample: `small = 3\nbig = 2\ntotal = small + big\nprint(total)`,
    glitchTrap: {
      brokenCode: `print("2" + "3")`,
      problem: "This is text. Python will glue '23'.",
      fix: 'print(2 + 3)',
    },
    mission: "Ask for the number of small and big crystals. Count the total.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["+", "print("] }),
    quiz: {
      question: "What will the code print(2 + 3) show?",
      options: ["23", "5", "2 + 3"],
      correctIndex: 1,
    },
    rewardAbility: "Gear of Counting",
  },
  {
    slug: "comparisons",
    number: "1-7",
    title: "Balance Lens",
    topic: "comparisons",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "The scales of choice. Comparison checks: yes or no. True = yes, False = no." },
    ],
    explanation: "Comparisons check 'is there enough'. > greater than, < less than, == equal. Result: True or False.",
    codeExample: `energy = 7\nprint(energy > 5)`,
    glitchTrap: {
      brokenCode: `level = 3\nprint(level = 3)`,
      problem: "For comparison we need ==, not =.",
      fix: 'print(level == 3)',
    },
    mission: "Check: energy is greater than 5, keys are at least 2, level equals 3.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: [">", "<", "=="] }),
    quiz: {
      question: "What does == mean?",
      options: ["put a value", "compare", "display text"],
      correctIndex: 1,
    },
    rewardAbility: "Balance Lens",
  },
  {
    slug: "if",
    number: "1-8",
    title: "Logic Key",
    topic: "if",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "if means 'if'. If the condition is true — the door opens." },
      { character: "Silas", text: "Don't forget the colon and the indent. The machine reads precisely." },
    ],
    explanation: "`if` starts an action only if the condition is true. After if put a colon, and the action — with an indent.",
    codeExample: `energy = 7\nif energy > 5:\n    print("Door open")`,
    glitchTrap: {
      brokenCode: `if energy > 5\n    print("Open")`,
      problem: "No colon after if.",
      fix: 'if energy > 5:\n    print("Open")',
    },
    mission: "Ask for the number of keys. If keys > 3 — print 'Passage open'.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["if", ":", "print("] }),
    quiz: {
      question: "What is required after an if condition?",
      options: ["a period", "a colon", "a quote"],
      correctIndex: 1,
    },
    rewardAbility: "Logic Key",
  },
  {
    slug: "if-else",
    number: "1-9",
    title: "Forked Gate",
    topic: "if else",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "else means 'otherwise'. A fork: one path or the other." },
      { character: "Lexa", text: "else is written without a condition, at the same level as if." },
    ],
    explanation: "`else` — choose one of two paths. If if didn't work, else runs.",
    codeExample: `keys = 2\nif keys >= 3:\n    print("Door open")\nelse:\n    print("Need more keys")`,
    glitchTrap: {
      brokenCode: `else\n    print("Closed")`,
      problem: "A colon is needed after else.",
      fix: 'else:\n    print("Closed")',
    },
    mission: "Ask for energy. If enough — print 'Bridge launched'. Otherwise — 'Not enough energy'.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["if", "else:", "print("] }),
    quiz: {
      question: "Does else have its own condition?",
      options: ["yes", "no"],
      correctIndex: 1,
    },
    rewardAbility: "Forked Gate",
  },
  {
    slug: "final-quest",
    number: "1-10",
    title: "Core Spark",
    topic: "final quest",
    mainCharacter: "Lyra",
    dialogue: [
      { character: "Lyra", text: "All parts are gathered. Now let's launch the machine!" },
      { character: "Dash", text: "Combine everything you've learned. This is your first real quest." },
    ],
    explanation: "Final quest: ask for name, age, and energy. Greet the hero. If energy is enough — launch the machine.",
    codeExample: `name = input("What is your name? ")\nage = int(input("How old are you? "))\nenergy = int(input("How much energy do you have? "))\nprint("Hello,", name)\nif energy >= 5:\n    print("Machine launched!")\nelse:\n    print("Not enough energy.")`,
    glitchTrap: {
      brokenCode: `energy = input("How much energy? ")\nif energy >= 5:`,
      problem: "input() gives text. You need int(input()) to compare numbers.",
      fix: 'energy = int(input("How much energy? "))\nif energy >= 5:',
    },
    mission: "Write a program that asks for name, age, energy; greets; launches the machine or reports insufficient energy.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["input(", "int(input(", "if", "else:", "print("] }),
    quiz: {
      question: "Which spell turns input into a number?",
      options: ["input()", "int()", "print()"],
      correctIndex: 1,
    },
    rewardAbility: "Core Spark",
  },
];
