export const stage1En = [
  {
    slug: "print",
    number: "1-1",
    title: "Voice Rune",
    topic: "print()",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "Greetings, apprentice! I'm Lexa. Today the machine will learn to speak." },
      { character: "Dash", text: "Your first mission is to make the machine pronounce a greeting!" },
    ],
    explanation:
      "`print()` is the 'show on screen' command. Inside the parentheses, write text in quotes, and the machine displays it on the panel.",
    codeExample: `print("Hello, workshop!")`,
    analogyDialogue: [
      { character: "Lexa", text: "Imagine a magic board in the workshop. Anything you write on it, everyone can see." },
      { character: "Novice", text: "How does the text get there?" },
      { character: "Lexa", text: "The print command is like a marker for the magic board. Say print('Hello') — and the word appears." },
      { character: "Novice", text: "What if I write without quotes?" },
      { character: "Lexa", text: "The board will think it's a spell name, not text. It gets confused." },
    ],
    childTakeaway:
      "print is a marker for the magic board. Write text in quotes — everyone sees. Without quotes, the board won't understand.",
    analogyQuest: "Write a command that shows on the magic board: 'I am ready for adventure!'",
    glitchTrap: {
      brokenCode: `print(Hello)`,
      problem: "Text without quotes.",
      fix: 'print("Hello")',
      analogy: "If you write a word on the board without a quote-frame, the board decides it's a spell name, not a message.",
    },
    mission: "Print three lines:\n1. My name is ...\n2. I came to start the machine\n3. Python Quest begins!",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ['print("', 'print("'] }),
    quiz: {
      question: "What does print() do?",
      options: ["saves a number", "shows text on the screen", "asks for an answer"],
      correctIndex: 1,
    },
    rewardAbility: "Voice Rune",
  },
  {
    slug: "strings",
    number: "1-2",
    title: "Seal of Words",
    topic: "strings and quotes",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "Words must be 'sealed' in quotes. Otherwise the machine won't understand it's text." },
      { character: "Silas", text: "Let us verify precision. Quotes are a frame for text." },
    ],
    explanation: "A string is text. In Python, text is always in quotes: double or single.",
    codeExample: `print("I am a hero")`,
    analogyDialogue: [
      { character: "Lexa", text: "Imagine a picture. To keep it from tearing, it's put in a frame." },
      { character: "Novice", text: "Are quotes the frame?" },
      { character: "Lexa", text: "Yes! Text in Python is like a picture. Without a quote-frame, it 'falls apart' and the machine doesn't understand these are words." },
      { character: "Novice", text: "What if the frame starts with one bracket and ends with another?" },
      { character: "Lexa", text: "Then the picture falls out. The frame must be the same on both sides." },
    ],
    childTakeaway: "Text in Python is like a picture in a frame. Quotes hold the words together. The frame must match.",
    analogyQuest: "Take three words and 'place' each one in a quote-frame so the machine reads them as text.",
    glitchTrap: {
      brokenCode: `print("I'm a hero')`,
      problem: "Different quotes.",
      fix: `print("I'm a hero")`,
      analogy: "If you start the frame with one bracket and end with another, the picture falls out and the words scatter.",
    },
    mission: "Print the hero's name, the workshop name, and the door password.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ['print("', 'print("', 'print("'] }),
    quiz: {
      question: "Where is the text written correctly?",
      options: ["print(Hello)", 'print("Hello")', "print Hello"],
      correctIndex: 1,
    },
    rewardAbility: "Seal of Words",
  },
  {
    slug: "variables",
    number: "1-3",
    title: "Memory Flask",
    topic: "variables",
    mainCharacter: "Lyra",
    dialogue: [
      { character: "Lyra", text: "A variable is a memory flask with a name. Put a value in — use it later." },
    ],
    explanation: "Variable = a box/flask with a name. On the left is the name, on the right is the value, = means 'put'.",
    codeExample: `hero_name = "Arin"\nprint(hero_name)`,
    analogyDialogue: [
      { character: "Lyra", text: "Imagine you have boxes with labels. One label says hero_name." },
      { character: "Novice", text: "What's inside?" },
      { character: "Lyra", text: "You put something in — then take it out by the label. hero_name = 'Arin' means you put the name into the box." },
      { character: "Novice", text: "What if the label is two words with a space?" },
      { character: "Lyra", text: "Then nobody will understand which box it is. The name must be one word or use an underscore." },
    ],
    childTakeaway: "A variable is a labeled box. Put a value in — use it later. The box name can't have spaces.",
    analogyQuest: "Invent three boxes with names and put the hero's name, city name, and pet name inside.",
    glitchTrap: {
      brokenCode: `hero name = "Arin"`,
      problem: "Space in the variable name.",
      fix: 'hero_name = "Arin"',
      analogy: "If the box name is two words with a space, nobody will understand how to open it.",
    },
    mission: "Create variables hero_name, city_name, pet_name and print them.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["=", "print("] }),
    quiz: {
      question: "What is inside the variable power = 5?",
      options: ["the name power", "the number 5", "the word print"],
      correctIndex: 1,
    },
    rewardAbility: "Memory Flask",
  },
  {
    slug: "input",
    number: "1-4",
    title: "Listening Gate",
    topic: "input()",
    mainCharacter: "Dash",
    dialogue: [
      { character: "Dash", text: "The machine must listen! The input() command asks a question and waits for an answer." },
    ],
    explanation: "`input()` — the machine asks a question and waits for the player's answer. It's better to save the answer in a variable.",
    codeExample: `name = input("What is your name? ")\nprint(name)`,
    analogyDialogue: [
      { character: "Dash", text: "Imagine a magic mirror. It asks you a question and remembers the answer." },
      { character: "Novice", text: "How does the mirror remember?" },
      { character: "Dash", text: "The answer needs to go into a variable-box. name = input('What is your name?') — the mirror asked, and the name landed in the box." },
      { character: "Novice", text: "What if the question has no quotes?" },
      { character: "Dash", text: "The mirror won't understand what you're asking. The question also needs a quote-frame." },
    ],
    childTakeaway: "input is a magic mirror that asks and remembers. Put the answer in a variable-box. The question goes in quotes.",
    analogyQuest: "Make the magic mirror ask for a favorite color and save the answer in a box.",
    glitchTrap: {
      brokenCode: `input(What is your name?)`,
      problem: "Question without quotes.",
      fix: 'input("What is your name? ")',
      analogy: "If you ask the mirror a question without quotes, it won't understand what you're asking.",
    },
    mission: "Ask for name, favorite color, and pet's name. Then print the answers.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["input(", "print("] }),
    quiz: {
      question: "Where is it best to save the player's answer?",
      options: ["in a variable", "in quotes", "in a comment"],
      correctIndex: 0,
    },
    rewardAbility: "Listening Gate",
  },
  {
    slug: "int-input",
    number: "1-5",
    title: "Number Converter",
    topic: "int(input())",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "input() gets text. But if you need a number — convert the text to a number with int()." },
    ],
    explanation: "`input()` gives text. `int()` converts text to a number. Wrap one inside the other.",
    codeExample: `age = int(input("How old are you? "))`,
    analogyDialogue: [
      { character: "Silas", text: "Imagine the mirror gives you a card with the digit '5' written as a word." },
      { character: "Novice", text: "How do you turn the word into a real number?" },
      { character: "Silas", text: "int is a magic lens. It turns a card with text '5' into a real digit 5." },
      { character: "Novice", text: "What if you add the word '5' and the number 1?" },
      { character: "Silas", text: "It's like adding an apple and a stone — the machine gets confused. You must turn the text into a number first." },
    ],
    childTakeaway: "int() is a magic lens. It turns text-number into a real number so you can count and compare.",
    analogyQuest: "The magic mirror asks for age. Turn the answer from a word into a real number using int.",
    glitchTrap: {
      brokenCode: `age = input("How old are you? ")\nnext_age = age + 1`,
      problem: "age is still text. You can't add text and a number.",
      fix: `age = int(input("How old are you? "))\nnext_age = age + 1`,
      analogy: "If you add the word '5' and the number 1, the magic machine gets confused — it's like adding an apple and a stone.",
    },
    mission: "Ask for age, number of keys, and crystals. Save them as numbers.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["int(input(", "="] }),
    quiz: {
      question: "Why do we need int()?",
      options: ["to display text", "to turn text into a number", "to create a condition"],
      correctIndex: 1,
    },
    rewardAbility: "Number Converter",
  },
  {
    slug: "arithmetic",
    number: "1-6",
    title: "Gear of Counting",
    topic: "arithmetic",
    mainCharacter: "Dash",
    dialogue: [
      { character: "Dash", text: "The counting gears are turning! Python can add, subtract, multiply, and divide." },
      { character: "Silas", text: "But be careful: numbers and text behave differently." },
    ],
    explanation: "Arithmetic counts resources. Add crystals, subtract spent keys.",
    codeExample: `small = 3\nbig = 2\ntotal = small + big\nprint(total)`,
    analogyDialogue: [
      { character: "Dash", text: "Imagine a blacksmith. He has metal ingots. He adds, subtracts, splits in half." },
      { character: "Novice", text: "Is Python also a blacksmith?" },
      { character: "Dash", text: "Yes! It just counts resources instead of ingots. small + big — added small and big crystals together." },
      { character: "Novice", text: "What if you add two tags with digits?" },
      { character: "Dash", text: "Then you won't get a number, you'll get a long tag '23'. To count, you need real numbers, not text." },
    ],
    childTakeaway: "Python counts like a blacksmith: adds, subtracts, multiplies, divides. But only real numbers, not text.",
    analogyQuest: "The blacksmith has 3 small and 2 big ingots. Count how many there are in total and show the result.",
    glitchTrap: {
      brokenCode: `print("2" + "3")`,
      problem: "This is text. Python will glue '23'.",
      fix: 'print(2 + 3)',
      analogy: "If you add two tags with digits, you won't get a number, you'll get a long tag '23'.",
    },
    mission: "Ask for the number of small and big crystals. Count the total.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["+", "print("] }),
    quiz: {
      question: "What will the code print(2 + 3) show?",
      options: ["23", "5", "2 + 3"],
      correctIndex: 1,
    },
    rewardAbility: "Gear of Counting",
  },
  {
    slug: "comparisons",
    number: "1-7",
    title: "Balance Lens",
    topic: "comparisons",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "The scales of choice. Comparison checks: yes or no. True = yes, False = no." },
    ],
    explanation: "Comparisons check 'is there enough'. > greater than, < less than, == equal. Result: True or False.",
    codeExample: `energy = 7\nprint(energy > 5)`,
    analogyDialogue: [
      { character: "Silas", text: "Imagine magic scales. You put energy on one side, a number on the other." },
      { character: "Novice", text: "What do they show?" },
      { character: "Silas", text: "The scales say: True — if the first side is heavier, or False — if not." },
      { character: "Novice", text: "What if you use = instead of ==?" },
      { character: "Silas", text: "Then the scales think you want to put something new on them, not compare. For comparing you need two equal signs." },
    ],
    childTakeaway: "Comparisons are magic scales. They check: greater, less, equal. Answer is True (yes) or False (no). Use == for comparing.",
    analogyQuest: "Put energy and the number 5 on the scales. Find out if energy is heavier, and show the answer.",
    glitchTrap: {
      brokenCode: `level = 3\nprint(level = 3)`,
      problem: "For comparison we need ==, not =.",
      fix: 'print(level == 3)',
      analogy: "If you put a single = on the scales instead of ==, the scales think you want to place something new, not compare.",
    },
    mission: "Check: energy is greater than 5, keys are at least 2, level equals 3.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: [">", "<", "=="] }),
    quiz: {
      question: "What does == mean?",
      options: ["put a value", "compare", "display text"],
      correctIndex: 1,
    },
    rewardAbility: "Balance Lens",
  },
  {
    slug: "if",
    number: "1-8",
    title: "Logic Key",
    topic: "if",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "if means 'if'. If the condition is true — the door opens." },
      { character: "Silas", text: "Don't forget the colon and the indent. The machine reads precisely." },
    ],
    explanation: "`if` starts an action only if the condition is true. After if put a colon, and the action — with an indent.",
    codeExample: `energy = 7\nif energy > 5:\n    print("Door open")`,
    analogyDialogue: [
      { character: "Lexa", text: "Imagine a hero standing before a door. On the door it says: 'You may enter if you have the key.'" },
      { character: "Novice", text: "What if the hero has the key?" },
      { character: "Lexa", text: "Then the door opens and the hero passes through." },
      { character: "Novice", text: "What if there is no key?" },
      { character: "Lexa", text: "Then the command inside if does not run." },
      { character: "Lexa", text: "In Python it looks like this:" },
      { character: "Lexa", text: "if has_key:\n    open_door()" },
      { character: "Novice", text: "So if is a check before an action?" },
      { character: "Lexa", text: "Yes. if decides: run the action or skip it. And the colon after if is a sign: 'The following commands only run if the check passes.'" },
    ],
    childTakeaway: "if is a guard at the door. It checks the condition. If true — the action is allowed. The colon after if signals the commands that follow only if the check passes.",
    analogyQuest: "A hero stands before a door. If they have more than 3 keys — the door opens. Write the check.",
    glitchTrap: {
      brokenCode: `if energy > 5\n    print("Open")`,
      problem: "No colon after if.",
      fix: 'if energy > 5:\n    print("Open")',
      analogy: "If the guard doesn't say 'stop' (the colon), he won't understand where the order begins.",
    },
    mission: "Ask for the number of keys. If keys > 3 — print 'Passage open'.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["if", ":", "print("] }),
    quiz: {
      question: "What is required after an if condition?",
      options: ["a period", "a colon", "a quote"],
      correctIndex: 1,
    },
    rewardAbility: "Logic Key",
  },
  {
    slug: "if-else",
    number: "1-9",
    title: "Forked Gate",
    topic: "if else",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "else means 'otherwise'. A fork: one path or the other." },
      { character: "Lexa", text: "else is written without a condition, at the same level as if." },
    ],
    explanation: "`else` — choose one of two paths. If if didn't work, else runs.",
    codeExample: `keys = 2\nif keys >= 3:\n    print("Door open")\nelse:\n    print("Need more keys")`,
    analogyDialogue: [
      { character: "Silas", text: "Imagine a fork in the forest. One sign says: 'If you have enough energy — the bridge is down.'" },
      { character: "Novice", text: "What if energy is not enough?" },
      { character: "Silas", text: "Then the 'Otherwise' sign triggers — and the hero takes a detour." },
      { character: "Novice", text: "Does 'Otherwise' have its own condition?" },
      { character: "Silas", text: "No. else is just the other path. It triggers if the first sign didn't fit. else is always without a condition." },
    ],
    childTakeaway: "if-else is a fork. One path if the condition is true. Another path if not. else has no condition.",
    analogyQuest: "At the fork there is a bridge. If energy is enough — the bridge lowers. Otherwise — find a detour. Write both branches.",
    glitchTrap: {
      brokenCode: `else\n    print("Closed")`,
      problem: "A colon is needed after else.",
      fix: 'else:\n    print("Closed")',
      analogy: "If the 'Otherwise' sign stands without a colon mark, travelers won't know which way to go.",
    },
    mission: "Ask for energy. If enough — print 'Bridge launched'. Otherwise — 'Not enough energy'.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["if", "else:", "print("] }),
    quiz: {
      question: "Does else have its own condition?",
      options: ["yes", "no"],
      correctIndex: 1,
    },
    rewardAbility: "Forked Gate",
  },
  {
    slug: "final-quest",
    number: "1-10",
    title: "Core Spark",
    topic: "final quest",
    mainCharacter: "Lyra",
    dialogue: [
      { character: "Lyra", text: "All parts are gathered. Now let's launch the machine!" },
      { character: "Dash", text: "Combine everything you've learned. This is your first real quest." },
    ],
    explanation: "Final quest: ask for name, age, and energy. Greet the hero. If energy is enough — launch the machine.",
    codeExample: `name = input("What is your name? ")\nage = int(input("How old are you? "))\nenergy = int(input("How much energy do you have? "))\nprint("Hello,", name)\nif energy >= 5:\n    print("Machine launched!")\nelse:\n    print("Not enough energy.")`,
    analogyDialogue: [
      { character: "Lyra", text: "Imagine a magic mechanism. To start it, you must assemble all parts: questions, numbers, checks." },
      { character: "Novice", text: "What do I do first?" },
      { character: "Lyra", text: "First ask for a name — put it in a box. Then age and energy — turn them into numbers with int()." },
      { character: "Novice", text: "And then?" },
      { character: "Lyra", text: "Greet the hero. Then check energy: if enough — machine launched, else — say energy is low." },
      { character: "Novice", text: "What if I forget to turn text into a number?" },
      { character: "Lyra", text: "Then the gears will jam. You need int() so the numbers are real." },
    ],
    childTakeaway: "The final quest is like assembling a mechanism. Connect questions, numbers, checks, and decisions. Together they launch the machine.",
    analogyQuest: "Assemble everything: ask for name, age, energy; greet the hero; launch the machine or say energy is low.",
    glitchTrap: {
      brokenCode: `energy = input("How much energy? ")\nif energy >= 5:`,
      problem: "input() gives text. You need int(input()) to compare numbers.",
      fix: 'energy = int(input("How much energy? "))\nif energy >= 5:',
      analogy: "If you put text instead of a number into the mechanism, the gears will jam — you must turn the text into a number first.",
    },
    mission: "Write a program that asks for name, age, energy; greets; launches the machine or reports insufficient energy.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["input(", "int(input(", "if", "else:", "print("] }),
    quiz: {
      question: "Which spell turns input into a number?",
      options: ["input()", "int()", "print()"],
      correctIndex: 1,
    },
    rewardAbility: "Core Spark",
  },
];
