export const stage1Ru = [
  {
    slug: "print",
    number: "1-1",
    title: "Руна Голоса",
    topic: "print()",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "Привет, ученик! Я Лекса. Сегодня машина научится говорить." },
      { character: "Dash", text: "Твоя первая миссия — заставить машину произнести приветствие!" },
    ],
    explanation:
      "`print()` — это команда 'покажи на экран'. Внутри скобок пишем текст в кавычках, и машина выводит его на панель.",
    codeExample: `print("Привет, мастерская!")`,
    glitchTrap: {
      brokenCode: `print(Привет)`,
      problem: "Текст без кавычек.",
      fix: 'print("Привет")',
    },
    mission: "Выведи три строки:\n1. Меня зовут ...\n2. Я пришёл запустить машину\n3. Python Quest начинается!",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ['print("', 'print("'] }),
    quiz: {
      question: "Что делает print()?",
      options: ["сохраняет число", "показывает текст на экране", "спрашивает ответ"],
      correctIndex: 1,
    },
    rewardAbility: "Руна Голоса",
  },
  {
    slug: "strings",
    number: "1-2",
    title: "Печать Слов",
    topic: "строки и кавычки",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "Слова нужно 'запечатать' в кавычки. Иначе машина не поймёт, что это текст." },
      { character: "Silas", text: "Проверим точность. Кавычки — рамка для текста." },
    ],
    explanation: "Строка — это текст. В Python текст всегда в кавычках: двойных или одинарных.",
    codeExample: `print("Я герой")`,
    glitchTrap: {
      brokenCode: `print("Я герой')`,
      problem: "Разные кавычки.",
      fix: `print("Я герой")`,
    },
    mission: "Выведи имя героя, название мастерской и пароль двери.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ['print("', 'print("', 'print("'] }),
    quiz: {
      question: "Где текст записан правильно?",
      options: ["print(Привет)", 'print("Привет")', "print Привет"],
      correctIndex: 1,
    },
    rewardAbility: "Печать Слов",
  },
  {
    slug: "variables",
    number: "1-3",
    title: "Колба Памяти",
    topic: "переменные",
    mainCharacter: "Lyra",
    dialogue: [
      { character: "Lyra", text: "Переменная — это колба памяти с именем. Кладём значение — используем позже." },
    ],
    explanation: "Переменная = коробка/колба с именем. Слева имя, справа значение, знак = значит 'положить'.",
    codeExample: `hero_name = "Арин"\nprint(hero_name)`,
    glitchTrap: {
      brokenCode: `hero name = "Арин"`,
      problem: "Пробел в имени переменной.",
      fix: 'hero_name = "Арин"',
    },
    mission: "Создай переменные hero_name, city_name, pet_name и выведи их.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["=", "print("] }),
    quiz: {
      question: "Что лежит в переменной power = 5?",
      options: ["имя power", "число 5", "слово print"],
      correctIndex: 1,
    },
    rewardAbility: "Колба Памяти",
  },
  {
    slug: "input",
    number: "1-4",
    title: "Врата Слушания",
    topic: "input()",
    mainCharacter: "Dash",
    dialogue: [
      { character: "Dash", text: "Машина должна слушать! Команда input() задаёт вопрос и ждёт ответ." },
    ],
    explanation: "`input()` — машина задаёт вопрос и ждёт ответ игрока. Ответ лучше сохранить в переменную.",
    codeExample: `name = input("Как тебя зовут? ")\nprint(name)`,
    glitchTrap: {
      brokenCode: `input(Как тебя зовут?)`,
      problem: "Вопрос без кавычек.",
      fix: 'input("Как тебя зовут? ")',
    },
    mission: "Спроси имя, любимый цвет и имя питомца. Потом выведи ответы.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["input(", "print("] }),
    quiz: {
      question: "Куда лучше сохранить ответ игрока?",
      options: ["в переменную", "в кавычки", "в комментарий"],
      correctIndex: 0,
    },
    rewardAbility: "Врата Слушания",
  },
  {
    slug: "int-input",
    number: "1-5",
    title: "Преобразователь Чисел",
    topic: "int(input())",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "input() получает текст. Но если нужно число — превращаем текст в число через int()." },
    ],
    explanation: "`input()` даёт текст. `int()` превращает текст в число. Оборачиваем одно в другое.",
    codeExample: `age = int(input("Сколько тебе лет? "))`,
    glitchTrap: {
      brokenCode: `age = input("Сколько тебе лет? ")\nnext_age = age + 1`,
      problem: "age пока текст. Нельзя складывать текст и число.",
      fix: `age = int(input("Сколько тебе лет? "))\nnext_age = age + 1`,
    },
    mission: "Спроси возраст, количество ключей и кристаллов. Сохрани как числа.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["int(input(", "="] }),
    quiz: {
      question: "Зачем нужен int()?",
      options: ["чтобы вывести текст", "чтобы превратить текст в число", "чтобы создать условие"],
      correctIndex: 1,
    },
    rewardAbility: "Преобразователь Чисел",
  },
  {
    slug: "arithmetic",
    number: "1-6",
    title: "Шестерёнка Счёта",
    topic: "арифметика",
    mainCharacter: "Dash",
    dialogue: [
      { character: "Dash", text: "Шестерёнки счёта вращаются! Python умеет складывать, вычитать, умножать и делить." },
      { character: "Silas", text: "Но будь внимателен: числа и текст ведут себя по-разному." },
    ],
    explanation: "Арифметика — считаем ресурсы. Складываем кристаллы, вычитаем потраченные ключи.",
    codeExample: `small = 3\nbig = 2\ntotal = small + big\nprint(total)`,
    glitchTrap: {
      brokenCode: `print("2" + "3")`,
      problem: "Это текст. Python склеит '23'.",
      fix: 'print(2 + 3)',
    },
    mission: "Спроси количество малых и больших кристаллов. Посчитай общее количество.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["+", "print("] }),
    quiz: {
      question: "Что покажет код print(2 + 3)?",
      options: ["23", "5", "2 + 3"],
      correctIndex: 1,
    },
    rewardAbility: "Шестерёнка Счёта",
  },
  {
    slug: "comparisons",
    number: "1-7",
    title: "Линза Баланса",
    topic: "сравнения",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "Весы выбора. Сравнение проверяет: да или нет. True = да, False = нет." },
    ],
    explanation: "Сравнения проверяют 'хватает ли'. > больше, < меньше, == равно. Результат: True или False.",
    codeExample: `energy = 7\nprint(energy > 5)`,
    glitchTrap: {
      brokenCode: `level = 3\nprint(level = 3)`,
      problem: "Для сравнения нужен ==, а не =.",
      fix: 'print(level == 3)',
    },
    mission: "Проверь: энергии больше 5, ключей не меньше 2, уровень равен 3.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: [">", "<", "=="] }),
    quiz: {
      question: "Что значит ==?",
      options: ["положить значение", "сравнить", "вывести текст"],
      correctIndex: 1,
    },
    rewardAbility: "Линза Баланса",
  },
  {
    slug: "if",
    number: "1-8",
    title: "Ключ Логики",
    topic: "if",
    mainCharacter: "Lexa",
    dialogue: [
      { character: "Lexa", text: "if значит 'если'. Если условие верно — дверь открывается." },
      { character: "Silas", text: "Не забудь двоеточие и отступ. Машина читает точно." },
    ],
    explanation: "`if` запускает действие только если условие верно. После if ставим двоеточие, а действие — с отступом.",
    codeExample: `energy = 7\nif energy > 5:\n    print("Дверь открыта")`,
    glitchTrap: {
      brokenCode: `if energy > 5\n    print("Открыто")`,
      problem: "Нет двоеточия после if.",
      fix: 'if energy > 5:\n    print("Открыто")',
    },
    mission: "Спроси количество ключей. Если ключей больше 3 — выведи 'Проход открыт'.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["if", ":", "print("] }),
    quiz: {
      question: "Что обязательно после условия if?",
      options: ["точка", "двоеточие", "кавычка"],
      correctIndex: 1,
    },
    rewardAbility: "Ключ Логики",
  },
  {
    slug: "if-else",
    number: "1-9",
    title: "Развилка",
    topic: "if else",
    mainCharacter: "Silas",
    dialogue: [
      { character: "Silas", text: "else значит 'иначе'. Развилка: один путь или другой." },
      { character: "Lexa", text: "else пишется без условия, на одном уровне с if." },
    ],
    explanation: "`else` — выбираем один из двух путей. Если if не сработал, выполняется else.",
    codeExample: `keys = 2\nif keys >= 3:\n    print("Дверь открыта")\nelse:\n    print("Нужно больше ключей")`,
    glitchTrap: {
      brokenCode: `else\n    print("Закрыто")`,
      problem: "После else нужно двоеточие.",
      fix: 'else:\n    print("Закрыто")',
    },
    mission: "Спроси энергию. Если хватает — выведи 'Мост запущен'. Иначе — 'Энергии мало'.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["if", "else:", "print("] }),
    quiz: {
      question: "У else есть своё условие?",
      options: ["да", "нет"],
      correctIndex: 1,
    },
    rewardAbility: "Развилка",
  },
  {
    slug: "final-quest",
    number: "1-10",
    title: "Искра Ядра",
    topic: "финальный квест",
    mainCharacter: "Lyra",
    dialogue: [
      { character: "Lyra", text: "Все части собраны. Теперь запустим машину!" },
      { character: "Dash", text: "Объедини всё, что узнал. Это твой первый настоящий квест." },
    ],
    explanation: "Финальный квест: спроси имя, возраст и энергию. Приветствуй героя. Если энергии хватает — запусти машину.",
    codeExample: `name = input("Как тебя зовут? ")\nage = int(input("Сколько тебе лет? "))\nenergy = int(input("Сколько у тебя энергии? "))\nprint("Привет,", name)\nif energy >= 5:\n    print("Машина запущена!")\nelse:\n    print("Энергии недостаточно.")`,
    glitchTrap: {
      brokenCode: `energy = input("Сколько энергии? ")\nif energy >= 5:`,
      problem: "input() даёт текст. Нужно int(input()) для сравнения чисел.",
      fix: 'energy = int(input("Сколько энергии? "))\nif energy >= 5:',
    },
    mission: "Напиши программу, которая спрашивает имя, возраст, энергию; приветствует; запускает машину или сообщает о нехватке энергии.",
    missionValidationRule: JSON.stringify({ type: "contains", targets: ["input(", "int(input(", "if", "else:", "print("] }),
    quiz: {
      question: "Какое заклинание превращает ввод в число?",
      options: ["input()", "int()", "print()"],
      correctIndex: 1,
    },
    rewardAbility: "Искра Ядра",
  },
];
